### ISSUE TITLE
Thanks for this!

### ISSUE THREAD

**Issue by Stevemoretz** [brc-dd/animated-tailwindcss#218]
This is not an issue just saying thanks and wishing you the best!
The docs are a bit hard to find, but other than that this is a gem!

**Comment by gpoole** [comment]
Yes great tool, exactly what I was looking for and works great. I found the lack of installation instructions or even a link to the docs in the main readme confusing and assumed it didn't have docs till I saw this issue. I think it would be helpful to add a link to the docs and put the installation instructions in the main readme @brc-dd if you're still maintaining it? I'm happy to send a PR if you'll merge it?

For anyone lost [the installation guide does exist](https://github.com/brc-dd/animated-tailwindcss/blob/main/docs/installation.md) and all the documentation is in the [docs folder](https://github.com/brc-dd/animated-tailwindcss/blob/main/docs).

**Comment by brc-dd** [comment]
There is a link on top in both GitHub and NPM. Is it hard to find?

<img width="450" alt="image" src="https://github.com/brc-dd/animated-tailwindcss/assets/40380293/388c18c8-ca8b-46a1-8763-aec2c62acbb9">

<img width="598" alt="image" src="https://github.com/brc-dd/animated-tailwindcss/assets/40380293/a085d85d-f877-42ce-9479-cb6c11ff98f9">

(BTW the logo itself is also clickable and opens the docs, yeah but that might not be obvious.)

**Comment by gpoole** [comment]
Unfortunately I missed both those links and I assume @Stevemoretz did as well. When I'm investigating a project on NPM or GitHub I typically scroll down to the README and quickly skim that for links to the documentation or website, so when I didn't see any I assumed it didn't have them. I've opened #220 proposing some inclusions that I typically find helpful.
